export const SET_SEARCH_INPUT = 'SET_SEARCH_INPUT';
export const SET_ARTISTS = 'SET_ARTISTS';
export const SET_CURRENT_SELECTION_INDEX = 'SET_CURRENT_SELECTION_INDEX';
export const SET_CURRENT_ARTIST_SELECTED = 'SET_CURRENT_ARTIST_SELECTED';
export const SET_CURRENT_ALBUM_SELECTED = 'SET_CURRENT_ALBUM_SELECTED';
export const SET_CURRENT_ALBUM_DETAILS = 'SET_CURRENT_ALBUM_DETAILS';
export const SET_ALBUM_LIST = 'SET_ALBUM_LIST';
export const SET_ALBUM_LIST_RESULT_TEXT = 'SET_ALBUM_LIST_RESULT_TEXT';

